stop-words = "../../../meta/data/lemur-stopwords.txt"
libsvm-modules = "../../../meta/deps/libsvm-modules/"
prefix = "/Users/Peter/PycharmProjects/Dietary-Supplement-Recommender/MeTA-data"
function-words = "../../../meta/data/function-words.txt"
punctuation = "../../../meta/data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "../../../meta/data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "../../../meta/data/sentence-boundaries/sentence-end-exceptions.txt"

corpus = "line.toml" # located inside dataset folder
dataset = "supplements"
index = "supplements-idx"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!
# indexer-num-threads = 8 # default value is system thread concurrency

query-judgements = "qrel.txt"
query-path = "queries.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"